trigger:
  - main
pool: Infrapipeline_2_VM
stages:
  - stage: terraform_install_to_terraform_validate
    jobs:
      - job: terraform_install_validate 
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment'
            backendServiceArm: 'newpipeline_2vm'
            backendAzureRmResourceGroupName: 'infra_pipeline_3012'
            backendAzureRmStorageAccountName: 'infrapipeline3012'
            backendAzureRmContainerName: 'infrapipeline3012'
            backendAzureRmKey: 'dev.terraform.tfstate'